version: '2'
services:         
  nginx:
    image: "nginx"
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./auth:/etc/nginx/auth
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
